name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.2.0
        with:
          github_user_name: AxelPCG
          outputs: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0 # Use uma versão disponível e estável
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
